Projeto/Blog/Blog.Web/Models/Login/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Blog.Web.Models.Login
{
    public class LoginViewModel
    {
        public string Email { get; set; }
        public string Senha { get; set; }
        public bool Lembrar { get; set; }
    }
}

Projeto/Blog/Blog.Web/Controllers/ContaController.cs
using Blog.Core.Data;
using Blog.Web.Models.Login;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace Blog.Web.Controllers
{
    public class ContaController : Controller
    {
        
        // GET: Conta
        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(LoginViewModel login, string returnUrl)
        {

            if (ModelState.IsValid)
            {
                using (EfDbContext db = new EfDbContext())
                {
                    var vLogin = db.Usuarios.Where(p => p.email.Equals(login.Email)).FirstOrDefault();
                    /*Verificar se a variavel vLogin está vazia. Isso pode ocorrer caso o usuário não existe. 
              Caso não exista ele vai cair na condição else.*/
                    if (vLogin != null)
                    {
                        /*Código abaixo verifica se a senha digitada no site é igual a senha que está sendo retornada 
     do banco. Caso não cai direto no else*/
                        if (Equals(vLogin.senha, login.Senha))
                        {
                            FormsAuthentication.SetAuthCookie(vLogin.email.ToString(), login.Lembrar);
                            if (Url.IsLocalUrl(returnUrl)
                            && returnUrl.Length > 1
                            && returnUrl.StartsWith("/")
                            && !returnUrl.StartsWith("//")
                            && returnUrl.StartsWith("/\\"))
                            {
                                return Redirect(returnUrl);
                            }

                            Session["id_usuario"] = vLogin.id_usuario;
                            Session["Usuario"] = vLogin.nome;
                            return RedirectToAction("Index", "Home");
                        }
                        /*Else responsável da validação da senha*/
                        else
                        {
                            /*Escreve na tela a mensagem de erro informada*/
                            ModelState.AddModelError("", "Senha informada Inválida!!!");
                            /*Retorna a tela de login*/
                            return View(new LoginViewModel());
                        }
                    }
                    else
                    {
                        /*Escreve na tela a mensagem de erro informada*/
                        ModelState.AddModelError("", "Usuario informado Inválida!!!");
                        /*Retorna a tela de login*/
                        return View(new LoginViewModel());
                    }
                    /*Else responsável por verificar se o usuário está ativo*/

                }
                /*Else responsável por verificar se o usuário existe*/

            }
            return View(new LoginViewModel());
        }

        public ActionResult Sair()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("/Home/Index");
        }

        public ActionResult Registrar()
        {
            return View();
        }
       

    }
}

Projeto/Blog/Blog.Web/Views/Conta/Login.cshtml
@model Blog.Web.Models.Login.LoginViewModel
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Login</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
</head>
<body>
    <script src="~/Scripts/bootstrap.js"></script>
    <div class="container">
        <div class="row">
            <div class='col-md-3'></div>
            <div class="col-md-6">
                <div class="login-box well">
                    @using (Html.BeginForm("Login", "Conta", new { returnUrl = Request.Url.Query }, FormMethod.Post, new { @class = "form-horizontal" }))
                    {
                        <legend>Login</legend>
                        <div class="form-group">
                            @Html.LabelFor(x => x.Email)
                            @Html.TextBoxFor(x => x.Email, new { @class = "form-control", placeholder = "E-mail" })

                        </div>
                                <div class="form-group">
                                    @Html.LabelFor(x => x.Senha)
                                    @Html.PasswordFor(x => x.Senha, new { @class = "form-control", placeholder = "Senha" })
                                </div>
                                <div class="input-group">
                                    <div class="checkbox">
                                        <label>
                                            @Html.CheckBoxFor(x => x.Lembrar) Remember me
                                        </label>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <input type="submit" class="btn btn-default btn-login-submit btn-block m-t-md" value="Entrar" />
                                </div>
                                <span class='text-center'><a href="/resetting/request" class="text-sm">Esqueceu a senha?</a></span>
                                <div class="form-group">
                                    <p class="text-center m-t-xs text-sm">Não é cadastrado?</p>
                                    <a href="/register/" class="btn btn-default btn-block m-t-md">Registrar</a>
                                </div>
                    }
                </div>
            </div>
            <div class='col-md-3'></div>
        </div>
    </div>
</body>
</html>