Projeto/Blog/Blog.Web/Areas/Admin/Models/PostViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Blog.Web.Areas.Admin.Models
{
    public class PostViewModel
    {
        public int id_post { get; set; }

        public int id_categoria { get; set; }


        public string titulo { get; set; }


        public string descricao { get; set; }


        public string meta_title { get; set; }
      
        public string imagem { get; set; }

     
        public string meta_description { get; set; }

        public DateTime? data_criacao { get; set; }

        public DateTime? data_alteracao { get; set; }
        [DataType(DataType.Upload)]
        public HttpPostedFileBase ImageUpload { get; set; }

        public string conteudo { get; set; }

        public bool ativo { get; set; }
    }
}

Projeto/Blog/Blog.Web/Areas/Admin/Controllers/PostController.cs
using Blog.Core.Data;
using Blog.Core.Domain;
using Blog.Web.Areas.Admin.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Blog.Web.Areas.Admin.Controllers
{
    public class PostController : Controller
    {

        private const string _ImagesPath = "~/Images/post";
        EfDbContext db = new EfDbContext();
        // GET: Admin/Post

        public ActionResult Index()
        {
            @ViewBag.Title = "Post";
            return View(db.Artigos.OrderBy(a=>a.descricao));
        }
        public JsonResult GetPost()
        {
            db.Configuration.ProxyCreationEnabled = false;
            var json = db.Artigos;
            return Json(json, JsonRequestBehavior.AllowGet);
        }
        public ActionResult Novo()
        {
            ViewBag.Title = "Post";
            ViewBag.Categorias = new SelectList(db.Categorias, "id_categoria", "descricao");
            return View();
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Novo(PostViewModel post)
        {
            if (ModelState.IsValid) { 
            if (post != null)
            {

                if (post.ImageUpload != null)
                {
                    // Delete exiting file
                    //System.IO.File.Delete(Path.Combine(Server.MapPath(_ImagesPath), carousel.CarouselImage));
                    // Save new file
                    string fileName = Guid.NewGuid() + Path.GetFileName(post.ImageUpload.FileName);
                    string path = Path.Combine(Server.MapPath(_ImagesPath), fileName);
                    post.ImageUpload.SaveAs(path);
                    post.imagem = fileName;

                }
                Artigos artigo = null;
                if (post.id_post == 0)
                {
                    artigo = new Artigos()
                    {
                        id_artigo = post.id_post,
                        ativo = post.ativo,
                        conteudo = post.conteudo,
                        data_alteracao = DateTime.Now,
                        data_criacao = DateTime.Now,
                        descricao = post.descricao == null ? "" : post.descricao,
                        titulo = post.titulo == null ? "" : post.titulo,
                        meta_title = post.meta_title == null ? "" : post.meta_title,
                        meta_description = post.meta_description == null ? "" : post.meta_description,
                        id_categoria = post.id_categoria,
                        imagem = post.imagem

                    };
                    db.Artigos.Add(artigo);

                }
                else
                {
                    artigo = db.Artigos.Find(post.id_post);
                    artigo.id_artigo = post.id_post;
                    artigo.ativo = post.ativo;
                    artigo.conteudo = post.conteudo;
                    artigo.data_alteracao = DateTime.Now;
                    artigo.data_criacao = DateTime.Now;
                    artigo.descricao = post.descricao == null ? "" : post.descricao;
                    artigo.titulo = post.titulo == null ? "" : post.titulo;
                    artigo.meta_title = post.meta_title == null ? "" : post.meta_title;
                    artigo.meta_description = post.meta_description == null ? "" : post.meta_description;
                    artigo.id_categoria = post.id_categoria;
                    artigo.imagem = post.imagem;
                }
                Usuarios user = db.Usuarios.FirstOrDefault(u => u.email == User.Identity.Name);
                artigo.id_usuario = user.id_usuario;
                db.SaveChanges();


                ViewBag.Title = "Post";
                return RedirectToAction("Index");
            }


        }
            return View(post);
        }
        public ActionResult Editar(int id)
        {
            if(id > 0)
            {
                PostViewModel post = (from p in db.Artigos
                           where p.id_artigo == id
                           select new PostViewModel()
                           {
                               ativo = p.ativo.Value,
                               conteudo = p.conteudo,
                               descricao = p.descricao,
                               id_categoria = p.id_categoria.Value,
                               id_post = p.id_artigo,
                               imagem = p.imagem,
                               meta_description = p.meta_description,
                               meta_title = p.meta_title,
                               titulo = p.titulo
                           }).First();
                ViewBag.Categorias = new SelectList(db.Categorias, "id_categoria", "descricao");
                return View("Novo", post);
            }
            ViewBag.Title = "Post";
            return View();
        }
    }
}

Projeto/Blog/Blog.Web/Controllers/BlogController.cs
using Blog.Core.Data;
using Blog.Core.Domain;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Blog.Web.Controllers
{
    public class BlogController : Controller
    {
        public int ProdutosPorPagina = 12;
        EfDbContext db = new EfDbContext();

        // GET: Blog
        public ActionResult Index()
        {
            
            return View(db.Artigos.Where(p=>p.ativo.Value));
        }
        public ActionResult Post(int id = 0)
        {
            var post = db.Artigos.FirstOrDefault(a => a.id_artigo == id);
            return View(post);
        }
        public ActionResult Categoria(int id)
        {
            var artigos = db.Artigos
                .Where(a => a.id_categoria == id)
                .OrderBy(a => a.data_criacao);
            return View("Index",artigos);
        }
        public ActionResult Tag(int id)
        {
            //var artigos = from tag in db.Tags
            //                           where tag.Artigos_Tags
            //                           .Any(c => c.Tags.id_tag == id)
            //                           select tag;
            var artigos = from tag in db.Tags
                           join artigo_tag in db.Artigos_Tags on tag.id_tag equals artigo_tag.id_tag
                           join artigo in db.Artigos on artigo_tag.id_artigo equals artigo.id_artigo
                           where tag.id_tag == id
                           select new Artigos
                           {
                               titulo = artigo.titulo,
                               descricao = artigo.descricao,
                               ativo = artigo.ativo.Value,
                               conteudo = artigo.conteudo,
                               meta_title = artigo.meta_title,
                               meta_description = artigo.meta_description,
                               data_alteracao = artigo.data_alteracao,
                               id_artigo = artigo.id_artigo,
                               data_criacao = artigo.data_criacao,
                               id_categoria = artigo.id_categoria,
                               id_usuario = artigo.id_usuario,
                               imagem = artigo.imagem,
                           };
                          

            return View("Index", artigos);
        }
        #region PartialView
        public PartialViewResult PostRecentes()
        {
            var posts = db.Artigos
                .OrderBy(p => p.data_criacao)
                .Take(5).Where(p=>p.ativo.Value);

            return PartialView(posts);
        }

        #endregion
    }
}

Projeto/Blog/Blog.Web/Controllers/CategoriasController.cs
using Blog.Core.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Blog.Web.Controllers
{
    public class CategoriasController : Controller
    {
        EfDbContext db = new EfDbContext();
        // GET: Categorias
        public PartialViewResult ListaCategorias()
        {
            var categorias = db.Categorias.OrderBy(p => p.descricao).Take(10);
            return PartialView(categorias);
        }
        
    }
}

Projeto/Blog/Blog.Web/Views/Blog/Index.cshtml
@model IEnumerable<Blog.Core.Domain.Artigos>
@{
    ViewBag.Title = "Blog";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container space-y-t-h space-y-b">

    <div class="row">

        <div class="col-md-9">

            <div class="row">

                <div class="col-md-12">

                    <ul class="blog-stander-sidebar">

                        
                        @foreach (var item in Model)
                        {
                            <li class="blog-stander-sidebar__details photography" data-category="photography">
                                <div class="post-img post-media">
                                    <a href="post-page.html">
                                        <img src="~/Images/post/@item.imagem" alt="">
                                    </a>
                                </div>
                                <div class="post-band">
                                    <div class="post-data">
                                        <h2>
                                            <a href='@Url.Action("Post","Blog",new {id=item.id_artigo })' class="post-title">@item.titulo</a> <h2>
                                                <ul class="post-data__group1">
                                                    <li class="post-categorize"> <a href="#">data de criação</a></li>
                                                    <li><time datetime="2015-04-26T12:04"> <strong>@string.Format("{0:dddd, MMMM d, yyyy}", item.data_criacao)</strong></time></li>
                                                </ul>

                                    </div>
                                    <!-- / post-data -->
                                    <div class="post-brief">
                                        
                                        <p>@item.descricao<a href='@Url.Action("Post","Blog",new {id=item.id_artigo })'>Continuar Lendo  </a> </p>

                                    </div>
                                    <ul class="post-data__group2">
                                        <li class="post-author"><a href="#"> <i class="fa fa-user"></i>@item.Usuarios.nome</a></li>
                                        <li class="post-comment"> <a href="#"><i class="fa fa-comment"></i> 1 </a> </li>
                                    </ul>
                                    <div class="tags">
                                        @foreach (var tag in item.Artigos_Tags)
                                        {
                                                <a href='@Url.Action("Tag","Blog",new {id=tag.id_tag})' class="tag"> @tag.Tags.descricao</a>

                                        }
                                    </div>
                                   
                                </div>
                                <!-- / post-band -->

                            </li>
                        }
                    


                    </ul>
                    <!-- #work-grid-item -->

                </div>
                <!-- / col-md-12 -->

            </div>
            <!-- / row -->

            <div class="row">

                <div class="col-md-12">

                    <div class="tags">
                        <a href="#" class="pagination-arow active">1</a>
                        <a href="#" class="pagination-arow">2</a>
                        <a href="#" class="pagination-arow">3</a>
                        <a href="#" class="pagination-arow">4</a>
                    </div>

                </div>
                <!-- end col-md-12 -->

            </div>
            <!-- end row-->

        </div>
        <!-- end col-md-9-->

        <div class="padding-top-half visible-sm-block visible-xs-block"></div>

        <div class="col-md-3">

            <aside class="blog-sidebar">

                <form id="searchfom" method="get" role="search">

                    <input type="search" style="background: #eee" placeholder="Pesquisar" name="search">

                </form>

               
                @Html.Action("PostRecentes", "Blog");
                @Html.Action("ListaCategorias", "Categorias");
                <section class="tags">
                    <h4 class="post-title">tags</h4>
                    <a href="#"> lifestyle</a>

                    <a href="#"> photography</a>

                    <a href="#"> news</a>

                    <a href="#"> music</a>

                    <a href="#"> health</a>

                    <a href="#"> science</a>

                    <a href="#"> design</a>

                    <a href="#"> life</a>

                </section>

            </aside>
            <!-- end blog sidebar -->

        </div>
        <!-- end col-md-3 -->

    </div>
    <!-- end row -->

</div>
<!-- end container -->


@section Scripts{

        
    
}

Projeto/Blog/Blog.Web/Views/Blog/PostRecentes.cshtml
@model IEnumerable<Blog.Core.Domain.Artigos>

<section class="recent-posts">

    <h4 class="post-title">Posts Recentes</h4>
    <ul>
        @foreach (var item in Model)
        {
            <li class="clearfix">
                <a href='@Url.Action("Post","Blog",new {id=item.id_artigo })'><img src="~/Images/post/@item.imagem" alt=""></a>
                <div class="recent-post__inner">
                    <a href="#"> @item.titulo</a>
                    <time datetime="2015-04-26T12:04"> <strong>@string.Format("{0:dddd, MMMM d, yyyy}", item.data_criacao)</strong></time>
                </div>
            </li>
        }
        
    </ul>

</section>